MedUA/Models/DoctorProfileViewModel.cs
namespace MedUA.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.Globalization;

    using MedUA.DAL;
    using MedUA.DAL.EntityModel;
    using MedUA.Resources;

    public class DoctorProfileViewModel
    {
        public string ImageSrc { get; set; }

        [Display(ResourceType = typeof(Resource), Name = ("Name"))]
        public string Name { get; set; }

        [Display(ResourceType = typeof(Resource), Name = ("Surname"))]
        public string Surname { get; set; }

        [Display(ResourceType = typeof(Resource), Name = ("Patronimic"))]
        public string Patronimic { get; set; }

        [Display(ResourceType = typeof(Resource), Name = ("Email"))]
        public string Email { get; set; }

        [Display(ResourceType = typeof(Resource), Name = ("DoctorProfileViewModelPosition"))]
        public string Position { get; set; }

        [Display(ResourceType = typeof(Resource), Name = ("DoctorProfileViewModelHospital"))]
        public string Hospital { get; set; }

        [Display(ResourceType = typeof(Resource), Name = ("DateOfBirth"))]
        public string DateOfBirth { get; set; }

        public static DoctorProfileViewModel Convert(DoctorUser user)
        {
            return new DoctorProfileViewModel()
            {
                Name = user.Name,
                Surname = user.Surname,
                Patronimic = user.Partonimic,
                DateOfBirth = user.DateOfBirth.ToString("d", CultureInfo.CurrentCulture),
                Hospital = $"{user.CurrentHospital.Name}. {user.CurrentHospital.Address}",
                Position = user.Position,
                ImageSrc = user.MaleFemale == MaleFemale.Female ? "/Images/doctor-woman.jpg" : "/Images/doctor-man.jpg",
                Email = user.Email
            };
        }
    }
}

MedUA/Controllers/DoctorController.cs
namespace MedUA.Controllers
{
    using System;
    using System.IO;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using System.Web.UI.WebControls;

    using Microsoft.AspNet.Identity;

    using MedUA.DAL;
    using MedUA.Data;
    using MedUA.Helpers;
    using MedUA.Resources;

    using Models;

    using Newtonsoft.Json;
    using Newtonsoft.Json.Linq;

    [Authorize(Roles = Roles.Doctor)]
    public class DoctorController : BaseApplicationUserController
    {

        public DoctorController()
        {
        }

        public DoctorController(ApplicationUserManager userManager, SignInManager signInManager, IApplicationDataProvider dataProvider)
            : base(userManager, signInManager, dataProvider)
        {
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var id = User.Identity.GetUserId();
            var doctor = await DataProvider.FindDoctorByIdAsync(id);
            return View(DoctorProfileViewModel.Convert(doctor));
        }

        [HttpGet]
        public async Task<ActionResult> ListPatients()
        {
            var model = await DataProvider.GetPatientListViewModelAsync(User.Identity.GetUserId());
            return this.View(model);
        }

        [HttpPost]
        public async Task<PartialViewResult> ListPatients(PatientListFilteredModel filteredModel)
        {
            var model = await DataProvider.GetPatientListViewModelAsync(User.Identity.GetUserId(), filteredModel);
            return this.PartialView("ListPatientsPartial", model);
        }


        [HttpGet]
        public async Task<ActionResult> Details(string patientId)
        {
            if (string.IsNullOrEmpty(patientId))
            {
                return this.View("Error");
            }
            var doctorId = this.User.Identity.GetUserId();
            var patientUser = await this.UserManager.FindByIdAsync(patientId);
            var listEntries = this.DataProvider.GetListEntries(patientId, doctorId);
            var researchList = await DataProvider.GetResearches(ResearchSettlementScope.Settlement, this.User.Identity.GetUserId());
            var researchHistory = await DataProvider.GetListResearches(patientId);
            var regions = DataProvider.GetRegions(doctorId);
            return this.View("PatientHistory", new EntryHistoryViewModelList() { EntryHistory = listEntries, PatientId = patientId, PatientSurnameName = $"{patientUser.Surname} {patientUser.Name}", ResearchList = researchList, Regions = regions, ResearchHistory = researchHistory });
        }

        [HttpPost]
        public PartialViewResult PatientHistory(string patientId)
        {
            using (var req = Request.InputStream)
            {
                req.Seek(0, SeekOrigin.Begin);
                using (var streamReader = new StreamReader(req))
                {
                    var json = streamReader.ReadToEnd();
                    var patientHistory = JsonConvert.DeserializeObject<HistoryGetViewModel>(json);
                    var skip = patientHistory.Skip * PageConstants.PageCount;
                    return this.PartialView(
                        "PatientHistoryPartial",
                        this.DataProvider.GetListEntries(
                            patientId,
                            doctorId: patientHistory.FilterDoctor ? User.Identity.GetUserId() : null,
                            take: patientHistory.Page * PageConstants.PageCount - skip,
                            skip: skip));
                }
            }
        }

        [HttpPost]
        public async Task<PartialViewResult> ResearchHistory(string patientId)
        {
            using (var req = Request.InputStream)
            {
                req.Seek(0, SeekOrigin.Begin);
                using (var streamReader = new StreamReader(req))
                {
                    var json = streamReader.ReadToEnd();
                    var researchHistory = JsonConvert.DeserializeObject<HistoryGetViewModel>(json);
                    var skip = researchHistory.Skip * PageConstants.PageCount;
                    return this.PartialView(
                        "ResearchHistoryPartial",
                        await this.DataProvider.GetListResearches(
                            patientId,
                            take: researchHistory.Page * PageConstants.PageCount - skip,
                            skip: skip));
                }
            }
        }

        [HttpGet]
        public ActionResult Search()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<ActionResult> Search(PatientSearchViewModel model)
        {
            var search = await DataProvider.GetPatientsSearch(await UserManager.FindByIdAsync(User.Identity.GetUserId()), model);
            return this.PartialView("SearchResultsPartial", search);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveNewEntry(EntryHistoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.DoctorId = User.Identity.GetUserId();
                var entry = DataProvider.SaveEntry(model);
                if (entry != null)
                {
                    return this.PartialView("PatientHistoryPartial", new[] { EntryHistoryViewModel.Convert(entry) });
                }
            }

            return null;
        }

        [HttpGet]
        public async Task<ActionResult> DoctorProfile(string doctorid)
        {
            var doctor = await DataProvider.FindDoctorByIdAsync(doctorid);
            return this.View("DoctorProfile", DoctorProfileViewModel.Convert(doctor));
        }

        [HttpPost]
        public async Task<ActionResult> AddPatient(AddPatientViewModel patient)
        {
            var isUserAdded = await DataProvider.AddPatient(User.Identity.GetUserId(), patient.Id);
            if (!isUserAdded)
            {
                return this.View("Error");
            }
            return this.RedirectToAction("ListPatients");
        }

        [HttpPost]
        public async Task<PartialViewResult> LoadResearchPickPartial(string patientId, int scope)
        {
            var scopeModel = (ResearchSettlementScope)scope;
            var researches = new ResearchPickViewModel() { PatientId = patientId, ResearchesList = await DataProvider.GetResearches(scopeModel, this.User.Identity.GetUserId()) };
            return this.PartialView("ResearchPickPartial", researches);
        }

        [HttpPost]
        public async Task<PartialViewResult> LoadResearches(string patientId, int scope, int research)
        {
            var scopeModel = (ResearchSettlementScope)scope;
            var researches = await DataProvider.GetResearches(scopeModel, this.User.Identity.GetUserId(), research);
            return this.PartialView("ResearchesPartial", new ResearchesPartialViewModelList(researches) { PatientId = patientId });
        }

        [HttpPost]
        public async Task<PartialViewResult> SaveResearchAppointment(NewAppointmentPartial newAppointmentPartial)
        {
            var resultDate = DateTime.Parse(newAppointmentPartial.Date);
            var resultTime = DateTime.Parse(newAppointmentPartial.Time);
            var resultDateTime = new DateTime(resultDate.Year, resultDate.Month, resultDate.Day, resultTime.Hour, resultTime.Minute, resultTime.Second);
            var result = await this.DataProvider.SaveResearchAppointment(newAppointmentPartial.HospitalResearchId, newAppointmentPartial.PatientId, resultDateTime);
            return this.PartialView("ResearchHistoryPartial", new[] { result });
        }

        public async Task<ActionResult> GetTimes(string date, int id)
        {
            var times = await DataProvider.GetAvailiableTimes(date, id);
            return Json(times, JsonRequestBehavior.AllowGet);
        }


    }
}

MedUA/Controllers/PatientController.cs
namespace MedUA.Controllers
{
    using System.IO;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity;

    using MedUA.DAL;
    using MedUA.Data;
    using MedUA.Models;
    using MedUA.Resources;

    using Newtonsoft.Json;

    [Authorize(Roles = Roles.Patient)]
    public class PatientController : BaseApplicationUserController
    {
        public PatientController()
        {
        }

        public PatientController(ApplicationUserManager userManager, SignInManager signInManager, IApplicationDataProvider dataProvider)
            : base(userManager, signInManager, dataProvider)
        {
        }
        
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            var patient = await UserManager.FindByIdAsync(User.Identity.GetUserId()) as PatientUser;
            return this.View(PatientProfileViewModel.Convert(patient));
        }

        [HttpGet]
        public async Task<ActionResult> PatientHistoryView()
        {
            var id = User.Identity.GetUserId();
            return View("PatientHistory",new EntryHistoryViewModelList() { EntryHistory = this.DataProvider.GetListEntries(id), ResearchHistory = await this.DataProvider.GetListResearches(id) });
        }

        [HttpPost]
        public PartialViewResult PatientHistory()
        {
            using (var req = Request.InputStream)
            {
                req.Seek(0, SeekOrigin.Begin);
                using (var streamReader = new StreamReader(req))
                {
                    var json = streamReader.ReadToEnd();
                    var patientHistory = JsonConvert.DeserializeObject<HistoryGetViewModel>(json);
                    var skip = patientHistory.Skip * PageConstants.PageCount;
                    return this.PartialView(
                        "PatientHistoryPartial",
                        this.DataProvider.GetListEntries(
                            User.Identity.GetUserId(),
                            take: patientHistory.Page * PageConstants.PageCount - skip,
                            skip: skip));
                }
            }
        }

        [HttpPost]
        public async Task<PartialViewResult> ResearchHistory(string patientId)
        {
            using (var req = Request.InputStream)
            {
                req.Seek(0, SeekOrigin.Begin);
                using (var streamReader = new StreamReader(req))
                {
                    var json = streamReader.ReadToEnd();
                    var researchHistory = JsonConvert.DeserializeObject<HistoryGetViewModel>(json);
                    var skip = researchHistory.Skip * PageConstants.PageCount;
                    return this.PartialView(
                        "ResearchHistoryPartial",
                        await this.DataProvider.GetListResearches(
                            patientId,
                            take: researchHistory.Page * PageConstants.PageCount - skip,
                            skip: skip));
                }
            }
        }
        [HttpGet]
        public async Task<ActionResult> DoctorProfile(string doctorId)
        {
            var doctor = await DataProvider.FindDoctorByIdAsync(doctorId);
            return this.View(DoctorProfileViewModel.Convert(doctor));

        }

        [HttpPost]
        public async Task<PartialViewResult> CancelAppointment(int appointmentId)
        {
            ResearchHistoryViewModel result = await DataProvider.CancelAppointment(appointmentId, User.Identity.GetUserId());
            return this.PartialView("ResearchHistoryPartial", new[] { result });
        }
    }
}

MedUA/Views/Shared/DoctorProfile.cshtml
@model MedUA.Models.DoctorProfileViewModel
<div class="form-group">
    <div class="col-md-3">
        <img src="@Model.ImageSrc" style="width:228px; height: 228px;" alt="Sample Photo" />
    </div>
    <div class="col-md-9">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "col-md-3" })
            @Html.DisplayFor(model => Model.Name, new { @class = "col-md-9" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Surname, new { @class = "col-md-3" })
            @Html.DisplayFor(model => Model.Surname, new { @class = "col-md-9" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Patronimic, new { @class = "col-md-3" })
            @Html.DisplayFor(model => Model.Patronimic, new { @class = "col-md-9" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "col-md-3" })
            @Html.DisplayFor(model => Model.Email, new { @class = "col-md-9" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, new { @class = "col-md-3" })
            @Html.DisplayFor(model => Model.Position, new { @class = "col-md-9" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Hospital, new { @class = "col-md-3" })
            @Html.DisplayFor(model => Model.Hospital, new { @class = "col-md-9" })
        </div>
    </div>
</div>

MedUA/Views/Shared/_ActionLinkPartial.cshtml
@using MedUA.DAL
@using MedUA.Helpers
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.Owin
@if (!Request.IsAuthenticated)
{
    @Html.ActionLink(@MedUA.Resources.Resource.MedUATitle, "Index", "Account", new { area = "" }, new { @class = "navbar-brand" })
}
else
{
    var userManager = Request.GetOwinContext().GetUserManager<ApplicationUserManager>();
    var user = userManager.FindById(User.Identity.GetUserId());
    var userName = $"{user.Surname} {user.Name}";
    if (User.IsInRole(MedUA.DAL.Roles.Patient))
    {
        @Html.ActionLink(userName, "Index", "Patient", new { area = "" }, new { @class = "navbar-brand" })
        ViewBag.Links = ViewBag.Links ?? new List<MvcHtmlString>();
        ViewBag.Links.Add(Html.ActionLink(MedUA.Resources.Resource.PatientLayoutLookMedicalCard, "PatientHistory", "Patient"));
    }
    else if (User.IsInRole(MedUA.DAL.Roles.Doctor))
    {
        @Html.ActionLink(userName, "Index", "Doctor", new { area = "" }, new { @class = "navbar-brand" })
    }
    else
    {
        @Html.ActionLink(@MedUA.Resources.Resource.MedUATitle, "Index", "Account", new { area = "" }, new { @class = "navbar-brand" })
    }
}

MedUA/Views/Shared/_Layout.cshtml
@using MedUA.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @MedUA.Resources.Resource.MedUATitle</title>
    <link href="~/Content/selectize/_template.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.Partial("_ActionLinkPartial")
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole(MedUA.DAL.Roles.Patient))
                    {
                        <li>@Html.ActionLink(MedUA.Resources.Resource.PatientLayoutLookMedicalCard, "PatientHistoryView", "Patient")</li>
                    }
                    @if (User.IsInRole(MedUA.DAL.Roles.Doctor))
                    {
                        <li>@Html.ActionLink(MedUA.Resources.Resource.DoctorLayoutMyPatient, "ListPatients", "Doctor")</li>
                        <li>@Html.ActionLink(MedUA.Resources.Resource.DoctorLayoutSearchPatient, "Search", "Doctor")</li>
                    }
                    @if (ViewBag.Links != null)
                    {
                        foreach (var mvcString in (List<MvcHtmlString>)ViewBag.Links)
                        {
                            <li>@mvcString</li>
                        }
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>